spring.application.name=demo

# Conexion PostgreSQL (Supabase - DIRECTA ?)
spring.datasource.url=jdbc:postgresql://db.nyjzvqrxzztsdhjxmpov.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=jcc3udGNW11rpxsm
server.port=${PORT:8080}
# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool (evita errores raros con conexiones)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ? IMPORTANTE (evita problemas con prepared statements)
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true